/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type ExpertiseReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "expertise";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  format?: "article" | "interview" | "news" | "resource";
  title?: string;
  slug?: Slug;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  author?: AuthorReference;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  featured?: boolean;
  videoUrl?: string;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  relatedExpertise?: Array<
    {
      _key: string;
    } & ExpertiseReference
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Expertise = {
  _id: string;
  _type: "expertise";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  socialImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | AuthorReference
  | CategoryReference
  | SanityFileAssetReference
  | ExpertiseReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Expertise
  | Author
  | Category
  | Seo
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[    _type == "post" &&    defined(slug.current) &&    ($format == null || format == $format)  ]  | order(publishedAt desc)  [$from...$to] {      _id,  format,  title,  "slug": slug.current,  excerpt,  publishedAt,  coverImage,  videoUrl,  author->{ name },  categories[]->{ title, "slug": slug.current }  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  format: "article" | "interview" | "news" | "resource" | null;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  videoUrl: string | null;
  author: {
    name: string | null;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: POSTS_COUNT_QUERY
// Query: count(*[    _type == "post" &&    defined(slug.current) &&    ($format == null || format == $format)  ])
export type POSTS_COUNT_QUERY_RESULT = number;

// Source: src/sanity/lib/queries.ts
// Variable: FEATURED_POST_QUERY
// Query: *[_type == "post" && defined(slug.current) && featured == true]    | order(publishedAt desc)[0] {      _id,  format,  title,  "slug": slug.current,  excerpt,  publishedAt,  coverImage,  videoUrl,  author->{ name },  categories[]->{ title, "slug": slug.current }  }
export type FEATURED_POST_QUERY_RESULT = {
  _id: string;
  format: "article" | "interview" | "news" | "resource" | null;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  videoUrl: string | null;
  author: {
    name: string | null;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: RECENT_POSTS_QUERY
// Query: *[    _type == "post" &&    defined(slug.current) &&    _id != $excludeId  ]  | order(publishedAt desc)[0...4] {      _id,  format,  title,  "slug": slug.current,  excerpt,  publishedAt,  coverImage,  videoUrl,  author->{ name },  categories[]->{ title, "slug": slug.current }  }
export type RECENT_POSTS_QUERY_RESULT = Array<{
  _id: string;
  format: "article" | "interview" | "news" | "resource" | null;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  videoUrl: string | null;
  author: {
    name: string | null;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: INTERVIEWS_QUERY
// Query: *[_type == "post" && format == "interview" && defined(slug.current)]    | order(publishedAt desc)[0...8] {      _id,  format,  title,  "slug": slug.current,  excerpt,  publishedAt,  coverImage,  videoUrl,  author->{ name },  categories[]->{ title, "slug": slug.current }  }
export type INTERVIEWS_QUERY_RESULT = Array<{
  _id: string;
  format: "article" | "interview" | "news" | "resource" | null;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  videoUrl: string | null;
  author: {
    name: string | null;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: LATEST_INTERVIEW_QUERY
// Query: *[_type == "post" && format == "interview" && defined(slug.current)]    | order(publishedAt desc)[0] {      _id,  format,  title,  "slug": slug.current,  excerpt,  publishedAt,  coverImage,  videoUrl,  author->{ name },  categories[]->{ title, "slug": slug.current }  }
export type LATEST_INTERVIEW_QUERY_RESULT = {
  _id: string;
  format: "article" | "interview" | "news" | "resource" | null;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  videoUrl: string | null;
  author: {
    name: string | null;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {      _id,  format,  title,  "slug": slug.current,  excerpt,  publishedAt,  coverImage,  videoUrl,  author->{ name },  categories[]->{ title, "slug": slug.current },    body,    file{ asset->{ url, originalFilename, size } },    relatedExpertise[]->{ title, "slug": slug.current }  }
export type POST_QUERY_RESULT = {
  _id: string;
  format: "article" | "interview" | "news" | "resource" | null;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  videoUrl: string | null;
  author: {
    name: string | null;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  file: {
    asset: {
      url: string | null;
      originalFilename: string | null;
      size: number | null;
    } | null;
  } | null;
  relatedExpertise: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)].slug.current
export type POST_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: src/sanity/lib/queries.ts
// Variable: RELATED_POSTS_QUERY
// Query: *[    _type == "post" &&    defined(slug.current) &&    count(relatedExpertise[@->slug.current == $expertise]) > 0  ]  | order(publishedAt desc)[0...3] {      _id,  format,  title,  "slug": slug.current,  excerpt,  publishedAt,  coverImage,  videoUrl,  author->{ name },  categories[]->{ title, "slug": slug.current }  }
export type RELATED_POSTS_QUERY_RESULT = Array<{
  _id: string;
  format: "article" | "interview" | "news" | "resource" | null;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  videoUrl: string | null;
  author: {
    name: string | null;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[\n    _type == "post" &&\n    defined(slug.current) &&\n    ($format == null || format == $format)\n  ]\n  | order(publishedAt desc)\n  [$from...$to] {\n    \n  _id,\n  format,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  coverImage,\n  videoUrl,\n  author->{ name },\n  categories[]->{ title, "slug": slug.current }\n\n  }\n': POSTS_QUERY_RESULT;
    '\n  count(*[\n    _type == "post" &&\n    defined(slug.current) &&\n    ($format == null || format == $format)\n  ])\n': POSTS_COUNT_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current) && featured == true]\n    | order(publishedAt desc)[0] {\n    \n  _id,\n  format,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  coverImage,\n  videoUrl,\n  author->{ name },\n  categories[]->{ title, "slug": slug.current }\n\n  }\n': FEATURED_POST_QUERY_RESULT;
    '\n  *[\n    _type == "post" &&\n    defined(slug.current) &&\n    _id != $excludeId\n  ]\n  | order(publishedAt desc)[0...4] {\n    \n  _id,\n  format,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  coverImage,\n  videoUrl,\n  author->{ name },\n  categories[]->{ title, "slug": slug.current }\n\n  }\n': RECENT_POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && format == "interview" && defined(slug.current)]\n    | order(publishedAt desc)[0...8] {\n    \n  _id,\n  format,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  coverImage,\n  videoUrl,\n  author->{ name },\n  categories[]->{ title, "slug": slug.current }\n\n  }\n': INTERVIEWS_QUERY_RESULT;
    '\n  *[_type == "post" && format == "interview" && defined(slug.current)]\n    | order(publishedAt desc)[0] {\n    \n  _id,\n  format,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  coverImage,\n  videoUrl,\n  author->{ name },\n  categories[]->{ title, "slug": slug.current }\n\n  }\n': LATEST_INTERVIEW_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    \n  _id,\n  format,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  coverImage,\n  videoUrl,\n  author->{ name },\n  categories[]->{ title, "slug": slug.current }\n,\n    body,\n    file{ asset->{ url, originalFilename, size } },\n    relatedExpertise[]->{ title, "slug": slug.current }\n  }\n': POST_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)].slug.current\n': POST_SLUGS_QUERY_RESULT;
    '\n  *[\n    _type == "post" &&\n    defined(slug.current) &&\n    count(relatedExpertise[@->slug.current == $expertise]) > 0\n  ]\n  | order(publishedAt desc)[0...3] {\n    \n  _id,\n  format,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  coverImage,\n  videoUrl,\n  author->{ name },\n  categories[]->{ title, "slug": slug.current }\n\n  }\n': RELATED_POSTS_QUERY_RESULT;
  }
}
